### ISSUE TITLE
tandem x tile index

### ISSUE THREAD

**Issue by justinelliotmeyers** [dshean/tandemx#1]
@dshean do you have a shapefile index of all the bounding boxes globally with their associated names?  Thanks!

**Comment by dshean** [comment]
I don't, but this would be pretty easy to do - the tile names are based on lat and lon in degrees (e.g., N49E010).  Just need to define polygons for each 1x1° tile, or use an existing set of polygons (e.g., from another global product on 1x1° tiles).  And I would recommend geojson rather than shp for something like this.

**Comment by justinelliotmeyers** [comment]
https://github.com/justinelliotmeyers/TanDEM-X_GRID_INDEX

Directly from DLR. Thanks for the response!
